### ISSUE TITLE
Make compatible with Sphinx 2.0

### ISSUE THREAD

**Issue by t-b** [byte-physics/doxygen-filter-ipf#2]
Error:

```
E:\projekte\mies-igor\Packages\doc\file\_compilation_tester_utils_8ipf.rst:6: WARNING: Duplicate declaration, CompilationTester
E:\projekte\mies-igor\Packages\doc\file\_i_p_n_w_b___constants_8ipf.rst:6: WARNING: Invalid definition: Expected end of definition. [error a
t 47]
  const variable IPNWB::IGOR_TYPE_8BIT_INT = 0x008
  -----------------------------------------------^
E:\projekte\mies-igor\Packages\doc\file\_i_p_n_w_b___debugging_8ipf.rst:6: WARNING: Duplicate declaration, IPNWB
```

The culprit is https://github.com/byte-physics/doxygen-filter-ipf/blob/4a762588f5b627aa3b0e7410d887c19ea817d60f/doxygen-filter-ipf.awk#L296-L300 as we need a terminating `;`.

Traceback:
```
# Sphinx version: 2.0.0b2
# Python version: 3.6.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   reading sources... [  4%] file/_compilation_tester_8ipf
#   
#   reading sources... [  5%] file/_compilation_tester_utils_8ipf
#   
#   reading sources... [  6%] file/_i_p_n_w_b___constants_8ipf
#   
#   reading sources... [  6%] file/_i_p_n_w_b___debugging_8ipf
#   
#   reading sources... [  7%] file/_i_p_n_w_b___h_d_f5_helpers_8ipf
#   
# Loaded extensions:
#   sphinx.ext.mathjax (2.0.0b2) from c:\anaconda2\envs\py36\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from c:\anaconda2\envs\py36\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.1) from c:\anaconda2\envs\py36\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.1) from c:\anaconda2\envs\py36\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.1) from c:\anaconda2\envs\py36\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.2) from c:\anaconda2\envs\py36\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.10) from c:\anaconda2\envs\py36\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.imgmath (2.0.0b2) from c:\anaconda2\envs\py36\lib\site-packages\sphinx\ext\imgmath.py
#   sphinx.ext.todo (2.0.0b2) from c:\anaconda2\envs\py36\lib\site-packages\sphinx\ext\todo.py
#   breathe (4.11.1) from h:\projekte\devel\breathe\breathe\__init__.py
#   sphinxcontrib.fulltoc (unknown version) from c:\anaconda2\envs\py36\lib\site-packages\sphinxcontrib\fulltoc.py
Traceback (most recent call last):
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\cmd\build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\application.py", line 338, in build
    self.builder.build_update()
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\builders\__init__.py", line 326, in build_update
    len(to_build))
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\builders\__init__.py", line 339, in build
    updated_docnames = set(self.read())
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\builders\__init__.py", line 445, in read
    self._read_serial(docnames)
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\builders\__init__.py", line 467, in _read_serial
    self.read_doc(docname)
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\builders\__init__.py", line 511, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\io.py", line 323, in read_doc
    pub.publish()
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\core.py", line 217, in publish
    self.settings)
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\io.py", line 116, in read
    self.parse()
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\parsers.py", line 94, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    input_source=document['source'])
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, state, transitions)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "c:\anaconda2\envs\py36\lib\site-packages\docutils\parsers\rst\states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "h:\projekte\devel\breathe\breathe\directive\file.py", line 91, in run
    return self.handle_contents(file_, project_info)
  File "h:\projekte\devel\breathe\breathe\directive\file.py", line 61, in handle_contents
    node_list.extend(object_renderer.render(node_stack[0], context))
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 1285, in render
    result = method(self, node)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 626, in visit_compounddef
    nodelist.extend(self.render_iterable(node.innernamespace))
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 1295, in render_iterable
    output.extend(self.render(entry))
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 1285, in render
    result = method(self, node)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 902, in visit_ref
    return self.visit_compound(node, False, get_node_info=get_node_info)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 462, in visit_compound
    rendered_data = self.render(file_data, parent_context)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 1285, in render
    result = method(self, node)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 453, in visit_doxygendef
    return self.render(node.compounddef)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 1285, in render
    result = method(self, node)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 625, in visit_compounddef
    nodelist.extend(self.render_iterable(node.innerclass))
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 1295, in render_iterable
    output.extend(self.render(entry))
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 1285, in render
    result = method(self, node)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 902, in visit_ref
    return self.visit_compound(node, False, get_node_info=get_node_info)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 503, in visit_compound
    name, kind)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 483, in render_signature
    nodes = self.run_domain_directive(kind, self.context.directive_args[1], augment=augment)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 345, in run_domain_directive
    nodes = domain_directive.run()
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\domains\cpp.py", line 6616, in run
    return super().run()
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\directives\__init__.py", line 163, in run
    name = self.handle_signature(sig, signode)
  File "c:\anaconda2\envs\py36\lib\site-packages\sphinx\domains\cpp.py", line 6624, in handle_signature
    ast = self.parse_definition(parser)
  File "h:\projekte\devel\breathe\breathe\renderer\sphinxrenderer.py", line 38, in parse_definition
    ast = parser.parse_declaration("class")
TypeError: parse_declaration() missing 1 required positional argument: 'directiveType'

```

**Comment by t-b** [comment]
This was not our error but sphinx' error, fixed for 2.0.x in sphinx via https://github.com/sphinx-doc/sphinx/pull/6298.
